const {
    Program,
    BinaryExp,
    Literal,
    IdExp,
    Print,
    Assignment,
    NegationExp,
    WhileExp,
    Suite,
    ForExp,
    Call,
    Argument,
    SubscriptedRangeable,
    IfStmt,
    Break,
    Rule,
    Arr,
    FunctionDeclaration,
    ArrayType,
    Types,
    Param,
    Params,
    Return,
    VariableDeclaration,
  } = require('../ast');